spring:
  jpa:
    show-sql: true

subpilot:
  nomba:
    mock-mode: true   # Always use mock locally until keys arrive

logging:
  level:
    co.subpilot: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
